name: Build Dawn

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Build Windows MSVC x64 Debug",
            os: windows-latest,
            flavor: win_msvc_debug.txt
          }
    steps:
      - uses: actions/checkout@v1

      - name: Prepare Depot Tools
        shell: pwsh
        run: |
          git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
          $env:Path = '' + (Get-Location) + '/depot_tools;' + $env:Path
          gclient --version

      - name: Prepare Google Dawn
        shell: pwsh
        run: |
          $env:Path = '' + (Get-Location) + '/depot_tools;' + $env:Path
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN = '0'
          git clone https://dawn.googlesource.com/dawn
          pushd dawn
          cp scripts/standalone.gclient .gclient
          gclient sync
          popd

      - name: Configure build of Google Dawn
        shell: pwsh
        run: |
          $env:Path = '' + (Get-Location) + '/depot_tools;' + $env:Path
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN = '0'
          mkdir dawn/out
          cp flavors/${{ matrix.config.flavor }} dawn/out/args.gn
          pushd dawn
          gn gen out --target_cpu="x64"
          popd

      - name: Build Google Dawn
        shell: pwsh
        run: |
          $env:Path = '' + (Get-Location) + '/depot_tools;' + $env:Path
          $env:DEPOT_TOOLS_WIN_TOOLCHAIN = '0'
          ninja -C dawn/out dawn_native_shared dawn_proc_shared dawncpp